@startuml
class javax.swing.JPanel

class org.dedda.games.scheisse.gui.cpu.inventory.InventoryPanel{
    - TabbedGamePane tabbedGamePane
    - InventoryTablePanel tablePanel
    - HeaderBar headerBar
    - Player player
    + InventoryPanel(TabbedGamePane)
    + void cancelTransaction()
    - void initLayout()
}

javax.swing.JPanel <|-- org.dedda.games.scheisse.gui.cpu.inventory.InventoryPanel
@enduml