@startuml
class javax.swing.JMenuBar

class org.dedda.games.scheisse.gui.cpu.MenuBar{
    - Gui gui
    - Game game
    + MenuBar(Gui)
    - void init()
    - void exit(int)
}

javax.swing.JMenuBar <|-- org.dedda.games.scheisse.gui.cpu.MenuBar
@enduml