@startuml
abstract class org.dedda.games.scheisse.io.resource.Images{
    - {static} Toolkit tk
    + {static} int MAIN_MENU_START
    + {static} int MAIN_MENU_OPTIONS
    + {static} int MAIN_MENU_EXIT
    + {static} int MAIN_MENU_CLOSE
    + {static} int MAIN_MENU_MINIMIZE
    + {static} int GAME_CLOSE
    + {static} int GAME_MINIMIZE
    + {static} int GAME_MAXIMIZE
    - {static} Image[] images
    + {static} Image get(int)
}
@enduml