@startuml
class org.dedda.games.scheisse.main.Main{
    + {static} String VERSION
    + {static} String URLTEXT_VERSION
    + {static} String INSTALLATION_FOLDER
    + {static} String[] INSTALLATION_FILES
    - {static} String piUrl
    - {static} boolean online
    - {static} boolean debug
    - {static} State currentState
    - {static} boolean installed
    - {static} boolean newestInstalled
    - {static} String[] args
    --
    + {static} void main(String[])
    + {static} boolean checkInternetConnection()
    - {static} void initOnline()
    - {static} void parseArgs()
    - {static} boolean checkVersion()
    - {static} int startUp()
    - {static} void loadResources()
    - {static} int run()
    - {static} void exit(int)
    - {static} void readConfig()
    - {static} String getNewestVersion()
    - {static} boolean compareVersions()
    + {static} boolean checkInstallation()
    .. Getter & Setter ..
    + {static} State getCurrentState()
    + {static} void setCurrentState(State)
    + {static} boolean isDebug()
    + {static} void setDebug(boolean)
    + {static} boolean isInstalled()
    + {static} boolean isOnline()
    + {static} String getPiUrl()
}
@enduml