@startuml
class javax.swing.JPanel

class org.dedda.games.scheisse.gui.cpu.shop.ShopPanel{
    - TabbedGamePane tabbedGamePane
    - Player player
    - JProgressBar progressBar
    - ShopTablePanel tablePanel
    + ShopPanel(TabbedGamePane)
    - void initLayout()
    + void setProgress(int, int)
}

javax.swing.JPanel <|-- org.dedda.games.scheisse.gui.cpu.shop.ShopPanel
@enduml