@startuml
class org.dedda.games.scheisse.state.game.object.behavior.NPCJumpIfTrue{
    - String expression
    - int jumpPoint
    --
    + NPCJumpIfTrue(NPCScript)
    + boolean hasNextStep()
    + void nextStep()
    .. Getter & Setter ..
    + String getExpression()
    + void setExpression(String)
    + int getJumpPoint()
    + void setJumpPoint(int)
    + ScriptEngineManager getScriptEngineManager()
    + void setScriptEngineManager(ScriptEngineManager)
    + ScriptEngine getScriptEngine()
    + void setScriptEngine(ScriptEngine)
}
@enduml