@startuml
abstract class org.dedda.games.scheisse.state.game.item.filter.ItemFilter

class org.dedda.games.scheisse.state.game.item.filter.ItemArmorFilter{
    + {static} int MODE_BELOW
    + {static} int MODE_EXACT
    + {static} int MODE_ABOVE
    + long armor
    + int mode
    + ItemTypeFilter itemTypeFilter
    + ItemArmorFilter(long, int)
    + boolean accept(org.dedda.games.scheisse.entity.Item)
}

org.dedda.games.scheisse.state.game.item.filter.ItemFilter <|.. org.dedda.games.scheisse.state.game.item.filter.ItemArmorFilter
@enduml