@startuml
class org.dedda.games.scheisse.state.game.shop.ShopConnector{
    + {static} long NOT_AVAILABLE
    + List<Offer> getOffers()
    + List<Offer> getOffers(ItemType)
    + long getSellingPrice(long)
    + long getBuyingPrice(long)
    + long sell(long, long)
    + long buy(long, long)
}
@enduml