@startuml
abstract class org.dedda.games.scheisse.state.game.item.org.dedda.games.scheisse.entity.Item

class org.dedda.games.scheisse.io.resource.item.ItemLoader{
    + org.dedda.games.scheisse.entity.Item loadItem(File)
    + ArrayList<org.dedda.games.scheisse.entity.Item> loadAll(File)
}

class org.dedda.games.scheisse.state.game.item.org.dedda.games.scheisse.entity.Item -- org.dedda.games.scheisse.io.resource.item.ItemLoader : < loads from file
@enduml