@startuml
abstract class org.dedda.games.scheisse.state.game.item.filter.ItemFilter

class org.dedda.games.scheisse.state.game.item.filter.ItemValueFilter{
    + {static} int MODE_BELOW
    + {static} int MODE_EXACT
    + {static} int MODE_ABOVE
    + long value
    + int mode
    + ItemValueFilter(long, int)
    + boolean accept(org.dedda.games.scheisse.entity.Item)
}

org.dedda.games.scheisse.state.game.item.filter.ItemFilter <|.. org.dedda.games.scheisse.state.game.item.filter.ItemValueFilter
@enduml