@startuml
class org.dedda.games.scheisse.state.game.object.behavior.NPCWalkToDestination{
    # Point2D.Double destination
    --
    + NPCWalkToDestination(NPCScript)
    + boolean hasNextStep()
    + void nextStep()
    - void calcRestAmount
    .. Getter & Setter ..
    + Point2D.Double getDestination()
    + void setDestination(Point2D.Double)
}
@enduml