@startuml
class org.dedda.games.scheisse.state.game.map.soil.Soil{
    - {static} HashMap<Type, Image> imageMap
    - {static} HashMap<Type, Texture> textureMap
    - {static} HashMap<Type, Image> initImageMap()
    - {static} HashMap<Type, Texture> initTextureMap()
    + {static} void loadImages()
    + {static} void loadTextures()
    + {static} void init()
    + {static} HashMap<Type, Image> getImageMap()
    + {static} Image getImage(Type)
    + {static} HashMap<Type, Texture> getTextureMap()
    + {static} Texture getTexture(Type)
}
@enduml