@startuml
abstract class org.dedda.games.scheisse.state.game.object.behavior.NPCScriptAction{
    # NPCScript script
    # ScriptEngineManager scriptEngineManager
    # ScriptEngine scriptEngine
    + NPCScriptAction(NPCScript)
    + {abstract} boolean hasNextStep()
    + {abstract} void nextStep()
    + double evalDouble(String)
    + boolean evalBool(String)
    + String evalString(String)
}
@enduml