@startuml
class org.dedda.games.scheisse.state.game.inventory.Slot

class org.dedda.games.scheisse.state.game.inventory.Inventory{
    - ArrayList<Slot> slots
    - ArrayList<InventoryChangeListener> inventoryChangeListeners
    + Inventory()
    + Inventory(int)
    + void triggerChangeEvent()
    + void addItems(Item, long)
    + void addItems(long, long)
    + void removeItems(Item, long)
    + void removeItems(long, long)
    + int getSize()
    + void setSize(int)
    + ArrayList<Slot> getSlots()
    + void setSlots(ArrayList<Slot>)
    + void setSlot(int, Slot)
    + void addSlot(Slot)
    + void print()
    + boolean containsSlotWithItemId(long)
    + getSlotWithItemId(long)
    + void addInventoryChangeListener(InventoryChangeListener)
    + void removeInventoryChangeListener(InventoryChangeListener)
    + ArrayList<InventoryChangeListener> getInventoryChangeListeners()
}

org.dedda.games.scheisse.state.game.inventory.Slot -- org.dedda.games.scheisse.state.game.inventory.Inventory : < consists of
@enduml