@startuml
class org.dedda.games.scheisse.state.game.object.npc.NPC{
    # double maxSpeed
    # boolean evil
    # double direction
    # String name
    --
    + NPC(Point2D.Double)
    + NPC(Point2D.Double, double, boolean)
    + boolean canMove(double, double)
    + void move(double)
    + void rotate(double)
    + void attack(Person)
    + void getAttacked(Attack)
    + void render(Graphics2D)
    ..Getter & Setter ..
    + double getDirection()
    + void setDirection(double)
    + double getMaxSpeed()
    + void setMaxSpeed(double)
    + boolean isEvil()
    + void setEvil(boolean)
    + String getName()
    + void setName(String)
}
@enduml