@startuml
class java.lang.Exception

class org.dedda.games.scheisse.exception.gui.ResourcePackException{
    + {static} int UNDEFINED
    + {static} int ALREADY_REGISTERED
    + {static} int NO_SUCH_SPRITE
    + int code
    + ResourcePackException()
    + ResourcePackException(int)
    + ResourcePackException(String)
    + ResourcePackException(String, int)
    + ResourcePackException(Throwable)
    + ResourcePackException(Throwable, int)
    + ResourcePackException(String, Throwable)
    + ResourcePackException(String, Throwable, int)
}

java.lang.Exception <|-- org.dedda.games.scheisse.exception.gui.ResourcePackException
@enduml