@startuml
class org.dedda.games.scheisse.state.menu.MainMenu{
    + {static} int START_GAME
    + {static} int OPTIONS
    + {static} int EXIT
    - Graphics2D g2d
    - int selection
    + MainMenu(Graphics2D g2d)
    + int getSelection
    + void run()
    + void render(Graphics2D)
}
@enduml