@startuml
class org.dedda.games.scheisse.state.game.object.behavior.NPCJumpIfEqual{
    - String expected
    - String actual
    - int jumpPoint
    --
    + NPCJumpIfEqual(NPCScript)
    + boolean hasNextStep()
    + void nextStep()
    .. Getter & Setter ..
    + String getExpected()
    + void setExpected(String)
    + String getActual()
    + void setActual(String)
    + int getJumpPoint()
    + void setJumpPoint(int)
}
@enduml