@startuml
interface java.awt.event.MouseListener
interface java.awt.event.MouseMotionListener
interface java.awt.event.MouseWheelListener

class org.dedda.games.scheisse.gui.io.Mouse{
    + {static} int CLICKED
    + {static} int PRESSED
    + {static} int RELEASED
    + {static} int ENTERED
    + {static} int EXITED
    + {static} int DRAGGED
    + {static} int MOVED
    + {static} int WHEEL_MOVED
    - ArrayList<MouseAction> clickAction
    - ArrayList<MouseAction> pressAction
    - ArrayList<MouseAction> releaseAction
    - ArrayList<MouseAction> enterAction
    - ArrayList<MouseAction> exitAction
    - ArrayList<MouseAction> dragAction
    - ArrayList<MouseAction> moveAction
    - ArrayList<MouseAction> wheelAction
    --
    + Mouse(Frame)
    + Mouse(JFrame)
    + void addAction(MouseAction, int)
    + void mouseClicked(MouseEvent)
    + void mousePressed(MouseEvent)
    + void mouseReleased(MouseEvent)
    + void mouseEntered(MouseEvent)
    + void mouseExited(MouseEvent)
    + void mouseDragged(MouseEvent)
    + void mouseMoved(MouseEvent)
    + void mouseWheelMoved(MouseWheelEvent)
    .. Getter ..
    + ArrayList<MouseAction> getClickAction()
    + ArrayList<MouseAction> getPressAction()
    + ArrayList<MouseAction> getReleaseAction()
    + ArrayList<MouseAction> getEnterAction()
    + ArrayList<MouseAction> getExitAction()
    + ArrayList<MouseAction> getDragAction()
    + ArrayList<MouseAction> getMoveAction()
    + ArrayList<MouseAction> getWheelAction()
}

java.awt.event.MouseListener <|.. org.dedda.games.scheisse.gui.io.Mouse
java.awt.event.MouseMotionListener <|.. org.dedda.games.scheisse.gui.io.Mouse
java.awt.event.MouseWheelListener <|.. org.dedda.games.scheisse.gui.io.Mouse
@enduml