@startuml
class java.io.FileFilter
class java.lang.Exception
interface java.lang.Runnable
class javax.swing.JComboBox
class javax.swing.JFrame
class javax.swing.JPanel
class javax.swing.JScrollPane
abstract class javax.swing.table.AbstractTableModel
interface javax.swing.table.TableCellRenderer

!include org.dedda.games.scheisse.debug.SystemPrinter.puml
!include org.dedda.games.scheisse.exception.gl.GLInitalizationException.puml
!include org.dedda.games.scheisse.exception.gui.ResourcePackException.puml
!include org.dedda.games.scheisse.exception.ExceptionCode.puml
!include org.dedda.games.scheisse.gui.cpu.inventory.table.InventoryTable.puml
!include org.dedda.games.scheisse.gui.cpu.inventory.table.InventoryTableModel.puml
!include org.dedda.games.scheisse.gui.cpu.inventory.table.ItemIconCellRenderer.puml
!include org.dedda.games.scheisse.gui.cpu.inventory.CategoriesChangedEvent.puml
!include org.dedda.games.scheisse.gui.cpu.inventory.CategoriesChangeListener.puml
!include org.dedda.games.scheisse.gui.cpu.inventory.HeaderBar.puml
!include org.dedda.games.scheisse.gui.cpu.inventory.ActionComboBox.puml
!include org.dedda.games.scheisse.gui.cpu.inventory.ActionPanel.puml
!include org.dedda.games.scheisse.gui.cpu.inventory.InventoryPanel.puml
!include org.dedda.games.scheisse.gui.cpu.inventory.InventoryTablePanel.puml
!include org.dedda.games.scheisse.gui.cpu.inventory.InventoryTransactionEvent.puml
!include org.dedda.games.scheisse.gui.cpu.inventory.InventoryTransactionListener.puml
!include org.dedda.games.scheisse.gui.cpu.shop.ShopPanel.puml
!include org.dedda.games.scheisse.gui.cpu.shop.ShopSortingFilter.puml
!include org.dedda.games.scheisse.gui.cpu.shop.ShopSortingPanel.puml
!include org.dedda.games.scheisse.gui.cpu.shop.ShopSortingWindow.puml
!include org.dedda.games.scheisse.gui.cpu.shop.ShopTablePanel.puml
!include org.dedda.games.scheisse.gui.cpu.ContentContainer.puml
!include org.dedda.games.scheisse.gui.cpu.GamePanel.puml
!include org.dedda.games.scheisse.gui.cpu.Gui.puml
!include org.dedda.games.scheisse.gui.cpu.MenuBar.puml
!include org.dedda.games.scheisse.gui.cpu.TabbedGamePane.puml
!include org.dedda.games.scheisse.gui.io.action.KeyAction.puml
!include org.dedda.games.scheisse.gui.io.action.KeyActionInfo.puml
!include org.dedda.games.scheisse.gui.io.action.MouseAction.puml
!include org.dedda.games.scheisse.gui.io.action.MouseActionInfo.puml
!include org.dedda.games.scheisse.gui.io.Keyboard.puml
!include org.dedda.games.scheisse.gui.io.Mouse.puml
!include org.dedda.games.scheisse.state.game.inventory.InventoryChangeListener.puml
!include org.dedda.games.scheisse.io.net.HttpDownloader.puml
!include org.dedda.games.scheisse.io.resource.item.ItemLoader.puml
!include org.dedda.games.scheisse.io.resource.item.ItemWords.puml
!include org.dedda.games.scheisse.io.resource.world.npc.NPCScriptLoader.puml
!include org.dedda.games.scheisse.io.resource.world.WorldDirectoryFilter.puml
!include org.dedda.games.scheisse.io.resource.world.WorldLoader.puml
!include org.dedda.games.scheisse.io.resource.BinaryResource.puml
!include org.dedda.games.scheisse.io.resource.Images.puml
!include org.dedda.games.scheisse.io.resource.Resource.puml
!include org.dedda.games.scheisse.io.resource.SaveGameLoader.puml
!include org.dedda.games.scheisse.io.resource.SaveGameWords.puml
!include org.dedda.games.scheisse.io.FileInput.puml
!include org.dedda.games.scheisse.io.FileOutput.puml
!include org.dedda.games.scheisse.io.GameDataWords.puml
!include org.dedda.games.scheisse.io.Installer.puml
!include org.dedda.games.scheisse.io.MapLoader.puml
!include org.dedda.games.scheisse.io.PackageReader.puml
!include org.dedda.games.scheisse.io.Unzip.puml
!include org.dedda.games.scheisse.main.FileTypes.puml
!include org.dedda.games.scheisse.main.Options.puml
!include org.dedda.games.scheisse.main.Main.puml
!include org.dedda.games.scheisse.state.game.fight.Attack.puml
!include org.dedda.games.scheisse.state.game.fight.AttackElement.puml
!include org.dedda.games.scheisse.state.game.inventory.CompareFilter.puml
!include org.dedda.games.scheisse.state.game.inventory.Inventory.puml
!include org.dedda.games.scheisse.state.game.inventory.InventoryChangeListener.puml
!include org.dedda.games.scheisse.state.game.inventory.Slot.puml
!include org.dedda.games.scheisse.state.game.item.filter.ItemArmorFilter.puml
!include org.dedda.games.scheisse.state.game.item.filter.ItemComplexFilter.puml
!include org.dedda.games.scheisse.state.game.item.filter.ItemFilter.puml
!include org.dedda.games.scheisse.state.game.item.filter.ItemLevelFilter.puml
!include org.dedda.games.scheisse.state.game.item.filter.ItemNameFilter.puml
!include org.dedda.games.scheisse.state.game.item.filter.ItemTypeFilter.puml
!include org.dedda.games.scheisse.state.game.item.filter.ItemValueFilter.puml
!include org.dedda.games.scheisse.state.game.level.Level.puml
!include org.dedda.games.scheisse.state.game.map.building.Building.puml
!include org.dedda.games.scheisse.state.game.map.building.Door.puml
!include org.dedda.games.scheisse.state.game.map.soil.Soil.puml
!include org.dedda.games.scheisse.state.game.map.soil.Soil.Type.puml
!include org.dedda.games.scheisse.state.game.map.Chunk.puml
!include org.dedda.games.scheisse.state.game.map.Map.puml
!include org.dedda.games.scheisse.state.game.map.MapObject.puml
!include org.dedda.games.scheisse.state.game.object.behavior.NPCJumpIfEqual.puml
!include org.dedda.games.scheisse.state.game.object.behavior.NPCJumpIfTrue.puml
!include org.dedda.games.scheisse.state.game.object.behavior.NPCRotate.puml
!include org.dedda.games.scheisse.state.game.object.behavior.NPCScript.puml
!include org.dedda.games.scheisse.state.game.object.behavior.NPCScriptAction.puml
!include org.dedda.games.scheisse.state.game.object.behavior.NPCWalk.puml
!include org.dedda.games.scheisse.state.game.object.behavior.NPCWalkToDestination.puml
!include org.dedda.games.scheisse.state.game.object.npc.NPC.puml
!include org.dedda.games.scheisse.state.game.object.GameObject.puml
!include org.dedda.games.scheisse.state.game.object.Person.puml
!include org.dedda.games.scheisse.state.game.object.PlayerObject.puml
!include org.dedda.games.scheisse.state.game.quest.Quest.puml
!include org.dedda.games.scheisse.state.game.shop.Offer.puml
!include org.dedda.games.scheisse.state.game.shop.ShopConnector.puml
!include org.dedda.games.scheisse.state.menu.Menu.puml
!include org.dedda.games.scheisse.state.menu.MainMenu.puml
!include org.dedda.games.scheisse.tool.Binary.puml
!include org.dedda.games.scheisse.tool.Distances.puml
!include org.dedda.games.scheisse.tool.Parse.puml

javax.swing.JPanel <|-- org.dedda.games.scheisse.gui.cpu.inventory.ActionPanel
javax.swing.JPanel <|-- org.dedda.games.scheisse.gui.cpu.inventory.InventoryPanel
javax.swing.JPanel <|-- org.dedda.games.scheisse.gui.cpu.shop.ShopPanel
org.dedda.games.scheisse.state.game.item.filter.ItemComplexFilter <|-- org.dedda.games.scheisse.gui.cpu.shop.ShopSortingFilter
javax.swing.JPanel <|-- org.dedda.games.scheisse.gui.cpu.shop.ShopSortingPanel
javax.swing.JFrame <|-- org.dedda.games.scheisse.gui.cpu.shop.ShopSortingWindow
javax.swing.JPanel <|-- org.dedda.games.scheisse.gui.cpu.shop.ShopTablePanel
org.dedda.games.scheisse.io.FileInput <|-- org.dedda.games.scheisse.io.resource.item.ItemLoader
org.dedda.games.scheisse.io.FileInput <|-- org.dedda.games.scheisse.io.resource.world.npc.NPCScriptLoader
org.dedda.games.scheisse.io.FileInput <|-- org.dedda.games.scheisse.io.MapLoader
org.dedda.games.scheisse.io.FileInput <|-- org.dedda.games.scheisse.io.PackageReader
java.io.FileFilter <|-- org.dedda.games.scheisse.io.resource.world.WorldDirectoryFilter
org.dedda.games.scheisse.io.FileInput <|-- org.dedda.games.scheisse.io.resource.world.WorldLoader
org.dedda.games.scheisse.io.FileInput <|-- org.dedda.games.scheisse.io.resource.SaveGameLoader
org.dedda.games.scheisse.state.game.object.behavior.NPCScriptAction <|-- org.dedda.games.scheisse.state.game.object.behavior.NPCJumpIfEqual
org.dedda.games.scheisse.state.game.object.behavior.NPCScriptAction <|-- org.dedda.games.scheisse.state.game.object.behavior.NPCJumpIfTrue
org.dedda.games.scheisse.state.game.object.behavior.NPCScriptAction <|-- org.dedda.games.scheisse.state.game.object.behavior.NPCRotate
org.dedda.games.scheisse.state.game.object.behavior.NPCScriptAction <|-- org.dedda.games.scheisse.state.game.object.behavior.NPCWalk
org.dedda.games.scheisse.state.game.object.behavior.NPCWalk <|-- org.dedda.games.scheisse.state.game.object.behavior.NPCWalkToDestination
org.dedda.games.scheisse.state.game.object.Person <|-- org.dedda.games.scheisse.state.game.object.npc.NPC
org.dedda.games.scheisse.state.game.object.GameObject <|-- org.dedda.games.scheisse.state.game.object.PlayerObject
org.dedda.games.scheisse.state.menu.Menu <|-- org.dedda.games.scheisse.state.menu.MainMenu
@enduml