@startuml
abstract class org.dedda.games.scheisse.state.game.object.Person{
    # long experience
    # String name
    # Point map
    # Point2D.Double lcation
    --
    + {abstract} void attack(Person)
    + {abstract} void getAttacked(Attack)
    .. Getter & Setter ..
    + Point2D.Double getLocation()
    + void setLocation(Point2D.Double)
    + Point getMap()
    + void setMap(Point)
    + String getName()
    + void setName(String)
    + long getExperience()
    + void setExperience(long)
}
@enduml