@startuml
class java.lang.Exception

class org.dedda.games.scheisse.exception.gl.GLInitalizationException{
    + GLInitializationException()
    + GLInitializationException(String)
    + GLInitializationException(Throwable)
    + GLInitializationException(String, Throwable)
}

java.lang.Exception <|-- org.dedda.games.scheisse.exception.gl.GLInitalizationException
@enduml