@startuml
abstract class org.dedda.games.scheisse.io.resource.Resource{
    + {static} String INSTALLATION_FOLDER
    + {static} String SAVAGAME_FOLDER
    + {static} String DATA_FOLDER
    + {static} String ITEM_FOLDER
    + {static} String IMAGE_FOLDER
    + {static} String TEMP_FOLDER
    + {static} String ITEM_ZIP
    + {static} String IMAGE_ZIP
    - {static} URL ITEM_URL
    - {static} URL IMAGE_URL
    + {static} HashMap<URL, String> getDownloadList()
    + {static} URL getIMAGE_URL()
    + {static} URL getITEM_URL()
}
@enduml