@startuml
class org.dedda.games.scheisse.state.game.map.Chunk{
    + {static} int CHUCK_SIZE
    - Point minLocation
    - Point maxLocation
    - ArrayList<MapObject> objects
    - Soil.Type[][] soil
    + Chunk(Point, Point)
    + void setObjects(ArrayList<MapObject>)
    + ArrayList<MapObject> getObjects()
    + void addObject(MapObject)
    + Soil.Type[][] getSoil()
    + void setSoil(Soil.Type[][])
    + void setSoilAbsolute(Point, Soil.Type)
    + void setSoilRelative(Point, Soil.Type)
    + Point getMinLocation()
    + Point getMaxLocation()
}
@enduml