@startuml
class javax.swing.JFrame

class org.dedda.games.scheisse.gui.cpu.shop.ShopSortingWindow{
    - ShopPanel shopPanel
    - ShopSortingPanel sortingPanel
    + ShopSortingWindow(ShopPanel)
}

javax.swing.JFrame <|-- org.dedda.games.scheisse.gui.cpu.shop.ShopSortingWindow
@enduml