@startuml
class org.dedda.games.scheisse.gui.cpu.inventory.ActionComboBox{
    + {static} String SELL
    + {static} String DESTROY
    - ArrayList<Strin> actions
    + InventoryActionComboBox()
}
@enduml