@startuml
class org.dedda.games.scheisse.io.FileOutput{
    - File file
    - FileWriter writer
    + FileOutput(File)
    + void write(String)
    + void writeArray(int[])
    + void writeCharArray(char[])
    + void writeLines(String[])
    + void writeHashMap(HashMap<String, String>)
    + void close()
}
@enduml