@startuml
abstract class org.dedda.games.scheisse.io.resource.item.ItemWords{
    + {static} String WAEPON
    + {static} String ARMOR
    + {static} String SHIELD
    + {static} String ID
    + {static} String TYPE
    + {static} String NAME
    + {static} String VALUE
    + {static} String ATTACK
    + {static} String SPRITE
}
@enduml