@startuml
class javax.swing.JTabbedPane
interface javax.swing.event.ChangeListener

class org.dedda.games.scheisse.gui.cpu.TabbedGamePane{
    - ContentContainer contentContainer
    - Gui gui
    - Game game
    - GamePanel gamePanel
    - InventoryPanel inventoryPanel
    - ShopPanel shopPanel
    - boolean inventoryOpen
    + TabbedGamePane(ContentContainer)
    + Gui getGui()
    + void stateChanged(ChangeEvent)
}

javax.swing.JTabbedPane <|-- org.dedda.games.scheisse.gui.cpu.TabbedGamePane
javax.swing.event.ChangeListener <|.. org.dedda.games.scheisse.gui.cpu.TabbedGamePane
@enduml