@startuml
class org.dedda.games.scheisse.io.FileInput{
    + String read(File)
    + Image readImage(File)
    + int[] readArray(File)
    + String[] getLines(File)
    + HashMap<String, String> getMap(File)
    + HashMap<String, String> getMap(File, boolean)
}
@enduml