@startuml
class org.dedda.games.scheisse.main.Options{
    + {static} File OPTIONS_FILE
    + {static} int KEY_MENU_UP
    + {static} int KEY_MENU_DOWN
    + {static} int KEY_MENU_LEFT
    + {static} int KEY_MENU_RIGHT
    + {static} int KEY_PAUSE_GAME
    + {static} int KEY_MENU_BACK
    - {static} boolean checkInternetConnection
    - {static} Dimension resolution
    --
    + {static} void initDefault()
    + {static} void load()
    + {static} void save()
    + {static} void set(HashMap<String, String>)
    + {static} void set(String, Object)
    .. Getter & Setter ..
    + {static} boolean isCheckInternetConnection()
    + {static} void setCheckInternetConnection(boolean)
    + {static} Dimension getResolution()
    + {static} void setResolution(Dimension)
}
@enduml