@startuml
class javax.swing.JComboBox

class org.dedda.games.scheisse.gui.cpu.inventory.ActionComboBox{
    + {static} String SELL
    + {static} String DESTROY
    - ArrayList<Strin> actions
    + InventoryActionComboBox()
}

javax.swing.JComboBox <|-- org.dedda.games.scheisse.gui.cpu.inventory.ActionComboBox
@enduml