@startuml
interface java.awt.event.KeyListener

class org.dedda.games.scheisse.gui.io.Keyboard{
    + {static} int TYPED
    + {static} int PRESSED
    + {static} int RELEASED
    - ArrayList<KeyAction> typeAction
    - ArrayList<KeyAction> pressAction
    - ArrayList<KeyAction> releaseAction
    + Keyboard(Frame)
    + Keyboard(JFrame)
    + void addAction(KeyAction, int)
    + void removeAction(KeyAction, int)
    + void keyTyped(KeyEvent)
    + void keyPressed(KeyEvent)
    + void keyReleased(KeyEvent)
    + ArrayList<KeyAction> getTypeAction()
    + ArrayList<KeyAction> getPressAction()
    + ArrayList<KeyAction> getReleaseAction()
}

java.awt.event.KeyListener <|.. org.dedda.games.scheisse.gui.io.Keyboard
@enduml