@startuml
class org.dedda.games.scheisse.state.game.map.Chunk

class org.dedda.games.scheisse.state.game.map.Map{
    - Dimension size
    - Dimension chunkGridSize
    - Chunk chunk[][]
    - ArrayList<MapObject> objects
    - Quest quest[]
    + Map(Dimension)
    - void init(Dimension, ArrayList<MapObject>)
    + void update()
    + void addObject(MapObject)
    - void addObjectToChunks(MapObject)
    + void setObjects(ArrayList<MapObject>)
    + void setObjects(MapObject[])
    + void setSoil(Point, Soil.Type)
    + void setSoil(Soil.Type[][])
    + Soil.Type[][] getSoil()
    + Dimension getSize()
    + Dimension getChunkGridSize()
    + Chunk[][] getChunk()
    + ArrayList<MapObject> getObjects()
    + void setQuest(Quest[])
    + Quest[] getQuest()
    + void print()
}

class org.dedda.games.scheisse.state.game.map.Chunk -- class org.dedda.games.scheisse.state.game.map.Map : < consists of
@enduml