@startuml
abstract class org.dedda.games.scheisse.state.game.object.GameObject{
    # Point2D.Double location
    --
    # GameObject(Point2D.Double)
    .. Getter & Setter ..
    + Point2D.Double getLocation()
    + void setLocation(Point2D.Double)
}
@enduml