@startuml
abstract class org.dedda.games.scheisse.state.game.item.filter.ItemFilter

class org.dedda.games.scheisse.state.game.inventory.CompareFilter{
    + {static} int MODE_BELOW
    + {static} int MODE_EXACT
    + {static} int MODE_ABOVE
    + {static} int CATEGORY_NAME
    + {static} int CATEGORY_VALUE
    + {static} int CATEGORY_MIN_XP
    + {static} int CATEGORY_DAMAGE
    + {static} int CATEGORY_ARMOR
    + int category
    + Item target
    + int mode
    + CompareFilter(int, Item, int)
    + boolean accept(Item)
}

org.dedda.games.scheisse.state.game.item.filter.ItemFilter <|-- org.dedda.games.scheisse.state.game.inventory.CompareFilter
@enduml