@startuml
class org.dedda.games.scheisse.gui.cpu.inventory.InventoryTablePanel{
    - TabbedGamePane tabbedGamePane
    - InventoryTable inventoryTable
    - InventoryTable actionTable
    - Inventory ActionInventory
    - InventoryActionPanel acitonPanel
    --
    + InventoryTablePanel(TabbedGamePane)
    - void initLayout()
    - ListSelectionListener getInventorySelectionListener()
    - ListSelectionListener getActionInventorySelectionListener()
    + void addTransactionListener(InventoryTransactionListener)
    + void removeTransactionListener(InventoryTransactionListener)
    + void cancelTransaction()
    .. Getter & Setter ..
    + InventoryTable getInventoryTable()
    + InventoryTable getActionTable()
    + InventoryActionPanel getActionPanel()
    + TabbedGamePane getTabbedGamePane()
}
@enduml