@startuml
abstract class org.dedda.games.scheisse_server.util.Config{
    - {static} String databaseUrl
    - {static} String databaseUser
    - {static} String databasePassword
    + {static} String getDatabaseUrl()
    + {static} String getDatabaseUser()
    + {static} String getDatabasePassword()
}
@enduml