@startuml
interface java.io.Serializable

class org.dedda.games.scheisse_server.transport.LoginContainer{
    + String name
    + String password
    + Login(String, String)
}

java.io.Serializable <|.. org.dedda.games.scheisse_server.transport.LoginContainer
@enduml