@startuml
(*)  --> "login"
--> "check version"
If "newer version availavle"
--> [Yes] "show message"
--> "set mode to offline"
--> "start loading resources"
else
--> [No] "set mode to online"
--> "start loading resources"
Endif
'If "input is verbose" then
'--> [Yes] "turn on verbosity"
'--> "run command"
'else
'--> "run command"
'Endif
-->(*)
@enduml